### PR TITLE
S4 Edits v2

### PR DESCRIPTION
**Pull request by siddk**
Mostly line edits, getting code to fit within display boxes, grammar/typos.

### CODE REVIEW

**Comment by srush** [comment]
Looks good, but linter is failing. 

Maybe the `:` should be `,` ? That might be my weird spelling quirk.

**Comment by siddk** [comment]
Linter is failing because of one line of code that in the blog post goes over the "display block" but the linter thinks should be formatted as one line.

I can totally change `:` to `,` -- that's just my weird spelling quirk haha.

**Comment by srush** [comment]
Yeah, lets go with ",". Otherwise should we call it done?

**Comment by siddk** [comment]
Ok - issue was that I configured the linter incorrectly - my bad! @srush - colons or commas?

**Comment by srush** [comment]
oops, think we crossed. Let's do commas

**Comment by siddk** [comment]
Commas have landed - ready to ship!

**Comment by siddk** [comment]
Think we crossed again - I think this is ready to merge?

**Pull request merged**
